# Generated by Django 4.2.5 on 2023-10-17 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_course_owner_lesson_owner_alter_lesson_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['pk'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
